### ISSUE TITLE
PAIN AND INCONVENIENCE (and questions)

### ISSUE THREAD

**Issue by personboithing** [sk7725/BetaMindy#162]
**Android**: *Android*

**138.1**: *The build number under the title in the main menu. Required.*

**Latest**: *(optional)*

**Anubanks, sources, and others. Crash my game when I tap on them. Same thing happens to claw and phase claw. When I try to place unit ducts and glass pipes my game crashes instantaneous. Also how do you get siloxol?**: *Explain your issue in detail.*

**Tap on anything anucoin related. Tap on claw or phase claw. Try to place unit duct or glase pipe.**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
1. bugs will be fixed when I get back to modding, which cannot be done right now due to real-life issues.
2. siloxol can be accessed by pumping the siloxol pools of Shar, which is a moon still in-dev.

**Comment by Sharlottes** [comment]
i think i fixed this bug by updating gradle dependencies, i will post PR as soon as possible

**Comment by Sharlottes** [comment]
https://github.com/sk7725/BetaMindy/commit/bb1f7c9c5398db0891caf23dd044cf29aa4819a5
bugfix there we go

**Comment by GreenGreenz** [comment]
Anucoin still doesn't work, I believe I am in a later android version though

**Comment by personboithing** [comment]
It no longer crashes, thank you so much.
